[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_prog = "5hcfuuJTzCW1ySkhECrm78AVBYZSp8udXnZhGrjx6cgy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
