// tests/counter_test.rs

use anchor_lang::prelude::*;
use anchor_lang::InstructionData;
use anchor_lang::ToAccountMetas;
use solana_program_test::*;
use solana_sdk::{
    account::ReadableAccount,
    signature::{Keypair, Signer},
    transaction::Transaction,
};

use counter_prog::{ // <-- Your local crate/module name
    id,
    instruction,       // Anchor automatically generates instruction builders for your program
    CounterState,
};

/// Convenience function to create a ProgramTest with our counter program.
fn program_test() -> ProgramTest {
    ProgramTest::new(
        // The first argument is the name of your Anchor program crate.
        // Make sure this matches the name in your Cargo.toml [lib] name or Anchor.toml.
        "counter_prog", 
        id(), 
        processor!(counter_prog::entry), // Entrypoint auto-generated by Anchor
    )
}

#[tokio::test]
async fn test_initialize_counter() {
    // 1) Create local test context
    let mut context = program_test().start_with_context().await;

    // 2) Generate a new keypair that will be the payer and authority
    let authority = Keypair::new();

    // Request an airdrop of SOL for the new authority so it can pay for transactions
    let tx = Transaction::new_signed_with_payer(
        &[
            system_instruction::transfer(
                &context.payer.pubkey(),
                &authority.pubkey(),
                1_000_000_000, // 1 SOL in lamports
            ),
        ],
        Some(&context.payer.pubkey()),
        &[&context.payer],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // 3) Derive a PDA or just create a Keypair for the counter account
    let counter_account = Keypair::new();

    // 4) Build the `initialize` instruction
    //    The auto-generated `instruction::initialize` helper from Anchor expects:
    //      - the program ID
    //      - the accounts struct
    //      - the function arguments
    let init_ix = instruction::initialize_counter(
        &id(),
        &counter_account.pubkey(),
        &authority.pubkey(),
        123, // the initial counter value
    );

    // 5) Create and send the transaction
    let tx = Transaction::new_signed_with_payer(
        &[init_ix],
        Some(&authority.pubkey()), // The payer (authority in this test)
        &[&authority, &counter_account], // Signers
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // 6) Fetch the on-chain account data and verify state
    let account_data = context
        .banks_client
        .get_account(counter_account.pubkey())
        .await
        .expect("counter_account not found")
        .expect("counter_account empty");

    // Deserialize our account data into CounterState
    let counter_state: CounterState = AnchorDeserialize::try_deserialize(&mut &account_data.data[..])
        .expect("failed to deserialize counter state");

    assert_eq!(counter_state.counter, 123);
    assert_eq!(counter_state.update_count, 1);
    assert_eq!(counter_state.authority, authority.pubkey());
}

#[tokio::test]
async fn test_increment_counter() {
    // 1) Create local test context
    let mut context = program_test().start_with_context().await;

    // 2) Keypairs: authority & the counter account
    let authority = Keypair::new();
    let counter_account = Keypair::new();

    // Airdrop some SOL to our authority
    let tx = Transaction::new_signed_with_payer(
        &[system_instruction::transfer(
            &context.payer.pubkey(),
            &authority.pubkey(),
            1_000_000_000,
        )],
        Some(&context.payer.pubkey()),
        &[&context.payer],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // 3) Initialize first so that we have a valid counter account
    let init_ix = instruction::initialize_counter(&id(), &counter_account.pubkey(), &authority.pubkey(), 10);
    let tx = Transaction::new_signed_with_payer(
        &[init_ix],
        Some(&authority.pubkey()),
        &[&authority, &counter_account],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // 4) Build the increment instruction
    let increment_ix = instruction::increment_counter(
        &id(),
        &counter_account.pubkey()
    );

    // 5) Send transaction
    let tx = Transaction::new_signed_with_payer(
        &[increment_ix],
        Some(&authority.pubkey()),
        &[&authority],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // 6) Check state
    let account_data = context
        .banks_client
        .get_account(counter_account.pubkey())
        .await
        .unwrap()
        .unwrap();

    let counter_state: CounterState = AnchorDeserialize::try_deserialize(&mut &account_data.data[..])
        .expect("failed to deserialize counter state");

    // Counter should have incremented from 10 to 11
    assert_eq!(counter_state.counter, 11);
    // Update count was 1 after initialization, so it should now be 2
    assert_eq!(counter_state.update_count, 2);
}

#[tokio::test]
async fn test_decrement_counter() {
    let mut context = program_test().start_with_context().await;

    let authority = Keypair::new();
    let counter_account = Keypair::new();

    // Airdrop
    let tx = Transaction::new_signed_with_payer(
        &[system_instruction::transfer(
            &context.payer.pubkey(),
            &authority.pubkey(),
            1_000_000_000,
        )],
        Some(&context.payer.pubkey()),
        &[&context.payer],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Initialize (set to 10 again)
    let init_ix = instruction::initialize_counter(&id(), &counter_account.pubkey(), &authority.pubkey(), 10);
    let tx = Transaction::new_signed_with_payer(
        &[init_ix],
        Some(&authority.pubkey()),
        &[&authority, &counter_account],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Decrement
    let decrement_ix = instruction::decrement_counter(
        &id(),
        &counter_account.pubkey()
    );
    let tx = Transaction::new_signed_with_payer(
        &[decrement_ix],
        Some(&authority.pubkey()),
        &[&authority],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Check state
    let account_data = context
        .banks_client
        .get_account(counter_account.pubkey())
        .await
        .unwrap()
        .unwrap();

    let counter_state: CounterState = AnchorDeserialize::try_deserialize(&mut &account_data.data[..])
        .expect("failed to deserialize counter state");

    // Counter should have decremented from 10 to 9
    assert_eq!(counter_state.counter, 9);
    assert_eq!(counter_state.update_count, 2);
}

#[tokio::test]
async fn test_set_counter() {
    let mut context = program_test().start_with_context().await;

    let authority = Keypair::new();
    let counter_account = Keypair::new();

    // Airdrop
    let tx = Transaction::new_signed_with_payer(
        &[system_instruction::transfer(
            &context.payer.pubkey(),
            &authority.pubkey(),
            1_000_000_000,
        )],
        Some(&context.payer.pubkey()),
        &[&context.payer],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Initialize at 50
    let init_ix = instruction::initialize_counter(&id(), &counter_account.pubkey(), &authority.pubkey(), 50);
    let tx = Transaction::new_signed_with_payer(
        &[init_ix],
        Some(&authority.pubkey()),
        &[&authority, &counter_account],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Set the counter to 999
    let set_ix = instruction::set_counter(
        &id(),
        &counter_account.pubkey(),
        &authority.pubkey(), // Must match the authority in the account
        999,
    );
    let tx = Transaction::new_signed_with_payer(
        &[set_ix],
        Some(&authority.pubkey()),
        &[&authority],
        context.last_blockhash,
    );
    context.banks_client.process_transaction(tx).await.unwrap();

    // Check
    let account_data = context
        .banks_client
        .get_account(counter_account.pubkey())
        .await
        .unwrap()
        .unwrap();

    let counter_state: CounterState = AnchorDeserialize::try_deserialize(&mut &account_data.data[..])
        .expect("failed to deserialize counter state");

    // Should now be 999
    assert_eq!(counter_state.counter, 999);
    // Should have incremented update_count by 2 (one for init, one for set)
    assert_eq!(counter_state.update_count, 2);
    assert_eq!(counter_state.authority, authority.pubkey());
}
